# Creation of Array (1D,2D and Multidimennsional array)

In [2]:
#Exp no. : 5

In [3]:
#Aim : Creation of Array (1D,2D and Multidimennsional array) using numpy

In [4]:
#Name : Ranjeet V. Telkhade
#Roll no. : 56 (DS-B52)
#Section : B 
#Subject : PE-I
#Date : 03-08-2024

In [5]:
import numpy as np

In [6]:
arr1=np.array([10,20,30,40,50])

In [7]:
arr1

array([10, 20, 30, 40, 50])

In [8]:
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [9]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [10]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [11]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])